identifier = "tools_five_test"
events = 1000000
repetitions = 30
cores = 20

arrival.distribution = "exponential"
service.distribution = "exponential"

[[class]]
cores = 1
arrival.prob = 0.5
service.mean = 0.5
service.distribution = "exponential"

[[class]]
cores = 2
arrival.prob = 0.1
service.mean = 0.83
service.distribution = "exponential"

[[class]]
cores = 5
arrival.prob = 0.2
service.mean = 1.25
service.distribution = "exponential"

[[class]]
cores = 10
arrival.prob = 0.19
service.mean = 3.33
service.distribution = "exponential"

[[class]]
cores = 15
arrival.prob = 0.01
service.mean = 10
service.distribution = "exponential"

[[pivot]]
policy = "fifo"
arrival.rate = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8]
